# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 810)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.995025, y2:1, stop:0 rgba(230, 230, 220, 255), stop:0.915423 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 2, 2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.image1Btn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.image1Btn.setFont(font)
        self.image1Btn.setObjectName("image1Btn")
        self.horizontalLayout_6.addWidget(self.image1Btn)
        self.remove1Btn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.remove1Btn.setFont(font)
        self.remove1Btn.setObjectName("remove1Btn")
        self.horizontalLayout_6.addWidget(self.remove1Btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image1_org = ImageView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image1_org.sizePolicy().hasHeightForWidth())
        self.image1_org.setSizePolicy(sizePolicy)
        self.image1_org.setObjectName("image1_org")
        self.horizontalLayout.addWidget(self.image1_org)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.combo_edit1 = QtWidgets.QComboBox(self.frame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.combo_edit1.setFont(font)
        self.combo_edit1.setObjectName("combo_edit1")
        self.combo_edit1.addItem("")
        self.combo_edit1.addItem("")
        self.combo_edit1.addItem("")
        self.combo_edit1.addItem("")
        self.combo_edit1.addItem("")
        self.verticalLayout.addWidget(self.combo_edit1)
        self.image1_edit = ImageView(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image1_edit.sizePolicy().hasHeightForWidth())
        self.image1_edit.setSizePolicy(sizePolicy)
        self.image1_edit.setObjectName("image1_edit")
        self.verticalLayout.addWidget(self.image1_edit)
        self.horizontalLayout.addWidget(self.frame1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addWidget(self.frame)
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        self.frame2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setLineWidth(2)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.image2Btn = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image2Btn.sizePolicy().hasHeightForWidth())
        self.image2Btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.image2Btn.setFont(font)
        self.image2Btn.setObjectName("image2Btn")
        self.horizontalLayout_10.addWidget(self.image2Btn)
        self.remove2Btn = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove2Btn.sizePolicy().hasHeightForWidth())
        self.remove2Btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.remove2Btn.setFont(font)
        self.remove2Btn.setObjectName("remove2Btn")
        self.horizontalLayout_10.addWidget(self.remove2Btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.image2_org = ImageView(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image2_org.sizePolicy().hasHeightForWidth())
        self.image2_org.setSizePolicy(sizePolicy)
        self.image2_org.setObjectName("image2_org")
        self.horizontalLayout_3.addWidget(self.image2_org)
        self.frame3 = QtWidgets.QFrame(self.frame2)
        self.frame3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_edit2 = QtWidgets.QComboBox(self.frame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_edit2.sizePolicy().hasHeightForWidth())
        self.combo_edit2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.combo_edit2.setFont(font)
        self.combo_edit2.setObjectName("combo_edit2")
        self.combo_edit2.addItem("")
        self.combo_edit2.addItem("")
        self.combo_edit2.addItem("")
        self.combo_edit2.addItem("")
        self.combo_edit2.addItem("")
        self.verticalLayout_2.addWidget(self.combo_edit2)
        self.image2_edit = ImageView(self.frame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image2_edit.sizePolicy().hasHeightForWidth())
        self.image2_edit.setSizePolicy(sizePolicy)
        self.image2_edit.setObjectName("image2_edit")
        self.verticalLayout_2.addWidget(self.image2_edit)
        self.horizontalLayout_3.addWidget(self.frame3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9.addWidget(self.frame2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.compo_output = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compo_output.sizePolicy().hasHeightForWidth())
        self.compo_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.compo_output.setFont(font)
        self.compo_output.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.995025, y2:1, stop:0 rgba(85, 255, 255, 255), stop:0.915423 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.995025, y2:1, stop:0 rgba(161, 172, 197, 255), stop:0.915423 rgba(255, 255, 255, 255));")
        self.compo_output.setObjectName("compo_output")
        self.compo_output.addItem("")
        self.compo_output.addItem("")
        self.compo_output.addItem("")
        self.verticalLayout_7.addWidget(self.compo_output)
        self.frame4 = QtWidgets.QFrame(self.centralwidget)
        self.frame4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame4.setLineWidth(1)
        self.frame4.setObjectName("frame4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame5 = QtWidgets.QFrame(self.frame4)
        self.frame5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame5.setObjectName("frame5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame6 = QtWidgets.QFrame(self.frame5)
        self.frame6.setObjectName("frame6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.compo_comp1 = QtWidgets.QComboBox(self.frame6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compo_comp1.sizePolicy().hasHeightForWidth())
        self.compo_comp1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.compo_comp1.setFont(font)
        self.compo_comp1.setObjectName("compo_comp1")
        self.compo_comp1.addItem("")
        self.compo_comp1.addItem("")
        self.compo_comp1.addItem("")
        self.horizontalLayout_4.addWidget(self.compo_comp1)
        self.verticalLayout_11.addWidget(self.frame6)
        self.Slider1 = QtWidgets.QSlider(self.frame5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider1.sizePolicy().hasHeightForWidth())
        self.Slider1.setSizePolicy(sizePolicy)
        self.Slider1.setStyleSheet("color: rgb(0, 0, 0);")
        self.Slider1.setMaximum(100)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider1.setObjectName("Slider1")
        self.verticalLayout_11.addWidget(self.Slider1)
        self.frame7 = QtWidgets.QFrame(self.frame5)
        self.frame7.setObjectName("frame7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.combo_mix1 = QtWidgets.QComboBox(self.frame7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_mix1.sizePolicy().hasHeightForWidth())
        self.combo_mix1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.combo_mix1.setFont(font)
        self.combo_mix1.setObjectName("combo_mix1")
        self.combo_mix1.addItem("")
        self.combo_mix1.addItem("")
        self.combo_mix1.addItem("")
        self.combo_mix1.addItem("")
        self.combo_mix1.addItem("")
        self.combo_mix1.addItem("")
        self.combo_mix1.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_mix1)
        self.slider_box1 = QtWidgets.QLineEdit(self.frame7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_box1.sizePolicy().hasHeightForWidth())
        self.slider_box1.setSizePolicy(sizePolicy)
        self.slider_box1.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_box1.setReadOnly(True)
        self.slider_box1.setObjectName("slider_box1")
        self.horizontalLayout_11.addWidget(self.slider_box1)
        self.verticalLayout_11.addWidget(self.frame7)
        self.verticalLayout_6.addWidget(self.frame5)
        self.verticalLayout_7.addWidget(self.frame4)
        self.frame8 = QtWidgets.QFrame(self.centralwidget)
        self.frame8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame8.setObjectName("frame8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalFrame = QtWidgets.QFrame(self.frame8)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame9 = QtWidgets.QFrame(self.verticalFrame)
        self.frame9.setObjectName("frame9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.compo_comp2 = QtWidgets.QComboBox(self.frame9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compo_comp2.sizePolicy().hasHeightForWidth())
        self.compo_comp2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.compo_comp2.setFont(font)
        self.compo_comp2.setObjectName("compo_comp2")
        self.compo_comp2.addItem("")
        self.compo_comp2.addItem("")
        self.compo_comp2.addItem("")
        self.horizontalLayout_8.addWidget(self.compo_comp2)
        self.verticalLayout_13.addWidget(self.frame9)
        self.Slider2 = QtWidgets.QSlider(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider2.sizePolicy().hasHeightForWidth())
        self.Slider2.setSizePolicy(sizePolicy)
        self.Slider2.setStyleSheet("color: rgb(0, 0, 0);")
        self.Slider2.setMaximum(100)
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setInvertedAppearance(False)
        self.Slider2.setInvertedControls(False)
        self.Slider2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider2.setObjectName("Slider2")
        self.verticalLayout_13.addWidget(self.Slider2)
        self.frame10 = QtWidgets.QFrame(self.verticalFrame)
        self.frame10.setObjectName("frame10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.combo_mix2 = QtWidgets.QComboBox(self.frame10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_mix2.sizePolicy().hasHeightForWidth())
        self.combo_mix2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.combo_mix2.setFont(font)
        self.combo_mix2.setObjectName("combo_mix2")
        self.combo_mix2.addItem("")
        self.combo_mix2.addItem("")
        self.combo_mix2.addItem("")
        self.combo_mix2.addItem("")
        self.combo_mix2.addItem("")
        self.combo_mix2.addItem("")
        self.combo_mix2.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_mix2)
        self.slider_box2 = QtWidgets.QLineEdit(self.frame10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_box2.sizePolicy().hasHeightForWidth())
        self.slider_box2.setSizePolicy(sizePolicy)
        self.slider_box2.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_box2.setReadOnly(True)
        self.slider_box2.setObjectName("slider_box2")
        self.horizontalLayout_12.addWidget(self.slider_box2)
        self.verticalLayout_13.addWidget(self.frame10)
        self.verticalLayout_5.addWidget(self.verticalFrame)
        self.verticalLayout_7.addWidget(self.frame8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame1.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.text_op1 = QtWidgets.QLineEdit(self.verticalFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_op1.sizePolicy().hasHeightForWidth())
        self.text_op1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_op1.setFont(font)
        self.text_op1.setAlignment(QtCore.Qt.AlignCenter)
        self.text_op1.setReadOnly(True)
        self.text_op1.setObjectName("text_op1")
        self.verticalLayout_8.addWidget(self.text_op1)
        self.output1_img = ImageView(self.verticalFrame1)
        self.output1_img.setObjectName("output1_img")
        self.verticalLayout_8.addWidget(self.output1_img)
        self.horizontalLayout_7.addWidget(self.verticalFrame1)
        self.verticalFrame2 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame2.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.text_op2 = QtWidgets.QLineEdit(self.verticalFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_op2.sizePolicy().hasHeightForWidth())
        self.text_op2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_op2.setFont(font)
        self.text_op2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_op2.setReadOnly(True)
        self.text_op2.setObjectName("text_op2")
        self.verticalLayout_9.addWidget(self.text_op2)
        self.output2_img = ImageView(self.verticalFrame2)
        self.output2_img.setObjectName("output2_img")
        self.verticalLayout_9.addWidget(self.output2_img)
        self.horizontalLayout_7.addWidget(self.verticalFrame2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_12, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1247, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInsert = QtWidgets.QMenu(self.menuFile)
        self.menuInsert.setObjectName("menuInsert")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImage_one = QtWidgets.QAction(MainWindow)
        self.actionImage_one.setObjectName("actionImage_one")
        self.actionImage_two = QtWidgets.QAction(MainWindow)
        self.actionImage_two.setObjectName("actionImage_two")
        self.menuInsert.addAction(self.actionImage_one)
        self.menuInsert.addAction(self.actionImage_two)
        self.menuFile.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image1Btn.setText(_translate("MainWindow", "Image one "))
        self.remove1Btn.setText(_translate("MainWindow", "Remove"))
        self.combo_edit1.setItemText(0, _translate("MainWindow", "Component"))
        self.combo_edit1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_edit1.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_edit1.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_edit1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.image2Btn.setText(_translate("MainWindow", "Image two"))
        self.remove2Btn.setText(_translate("MainWindow", "Remove"))
        self.combo_edit2.setItemText(0, _translate("MainWindow", "Component"))
        self.combo_edit2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_edit2.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_edit2.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_edit2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.compo_output.setItemText(0, _translate("MainWindow", "Select O/P"))
        self.compo_output.setItemText(1, _translate("MainWindow", "Output1"))
        self.compo_output.setItemText(2, _translate("MainWindow", "Output2"))
        self.lineEdit_3.setText(_translate("MainWindow", "Component 1"))
        self.compo_comp1.setItemText(0, _translate("MainWindow", "Image no"))
        self.compo_comp1.setItemText(1, _translate("MainWindow", "Image1"))
        self.compo_comp1.setItemText(2, _translate("MainWindow", "Image2"))
        self.combo_mix1.setItemText(0, _translate("MainWindow", "Component"))
        self.combo_mix1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_mix1.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_mix1.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_mix1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.combo_mix1.setItemText(5, _translate("MainWindow", "Uniform_mag"))
        self.combo_mix1.setItemText(6, _translate("MainWindow", "Uniform_phase"))
        self.lineEdit.setText(_translate("MainWindow", "Component 2"))
        self.compo_comp2.setItemText(0, _translate("MainWindow", "Image no"))
        self.compo_comp2.setItemText(1, _translate("MainWindow", "Image1"))
        self.compo_comp2.setItemText(2, _translate("MainWindow", "Image2"))
        self.combo_mix2.setItemText(0, _translate("MainWindow", "Component"))
        self.combo_mix2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.combo_mix2.setItemText(2, _translate("MainWindow", "Phase"))
        self.combo_mix2.setItemText(3, _translate("MainWindow", "Real"))
        self.combo_mix2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.combo_mix2.setItemText(5, _translate("MainWindow", "Uniform_mag"))
        self.combo_mix2.setItemText(6, _translate("MainWindow", "Uniform_phase"))
        self.text_op1.setText(_translate("MainWindow", "Output1"))
        self.text_op2.setText(_translate("MainWindow", "Output2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuInsert.setTitle(_translate("MainWindow", "Insert"))
        self.actionImage_one.setText(_translate("MainWindow", "Image one"))
        self.actionImage_two.setText(_translate("MainWindow", "Image two"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
